---
hosts: VWS
vars:
  target_host: PTC
vcenter_hostname: "DVSPTCVC01"
vcenter_datacenter: "PTC"
vcenter_validate_certs: false
vcenter_username: "Administrator@vsphere.local"
vcenter_password: !vault |
          $ANSIBLE_VAULT;1.2;AES256;vdiops
          61643763336463363235356532306564636135396261386330396634613833636635356539353333
          6636646433613162383131313062646134393531313262390a353239346634643330373231373130
          35653636636634393037363764646561333563646430346564643963623062613533666165343964
          6361353438663732380a346363303664306261656662633462323833313263653937383338633961
          33646565663134373330353731333733356561663131376237336562313862393338
vm_name: "{{ target_host }}"
vm_template: "mytemplate"
vm_folder: "{{ target_host }}"
